# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c16669e97f8829a858d9c61232e00810da9a33c9f22510f5274aa9d1c82c71f3dea8717716b50bb86b9d55080b44f82d62eadf5631189f68f33d4bd6b6424c2

test:
  secret_key_base: 0da3770a3433bc21023e4b6e206ddc845db2efbf540215b07d7fa86ae0600b1b1bce3dfd28264ec7add63357d9ff55b4a102db27bdc7ccf22f7fa52cbad89e89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
